version: '2.3'

services:
  tensorflow:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - 8888:8888
      - 6006:6006
    volumes:
      - ../notebooks:/tf
      - ../data:/data
